### ISSUE TITLE
啥时候发版本呀，鸿蒙系统马上上线了，没app用了

### ISSUE THREAD

**Issue by mx342** [mgz0227/legado-Harmony#126]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

啥时候发版本呀，鸿蒙系统马上上线了，没app用了

### 期望实现方式 / How to implement

啥时候发版本呀，鸿蒙系统马上上线了，没app用了

### 附加信息 / Additions

啥时候发版本呀，鸿蒙系统马上上线了，没app用了

### 效果演示 / Demo

啥时候发版本呀，鸿蒙系统马上上线了，没app用了

**Comment by mgz0227** [comment]
哪有那么快。。。别急

**Comment by liaoyu1992** [comment]
踢一脚，上线了么
