### ISSUE TITLE
IndexShelf页的一点小瑕疵

### ISSUE THREAD

**Issue by alphires1** [mgz0227/legado-Harmony#143]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新版依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在书架页初始化的时候，顶部三个书籍分类标题（小说 漫画 有声书），一开始未被选中的那两个是没有背景的（即BookMake中的backgroundImage），但是当它们被选中又继续切换到其他标题之后，标题的背景依然存在

### 复现步骤 / How to reproduce

在书架页切换或点击顶部三个分类标题

### 确认 / Assignment

- [X] #145

### 阅读版本 / Legado version

1.1

### Harmony OS版本 / Harmony OS version

OS 4

### 机型 / Model

preview

**Comment by MaoXiaoone** [comment]
麻烦提供bug截图，经过测试没出现该情况。

**Comment by alphires1** [comment]
![初始化](https://github.com/mgz0227/legado-Harmony/assets/153937346/2395922d-3823-472a-8ee1-581f11ed660f)
daga初始化进入
![点击漫画标签之后，小说标签的背景](https://github.com/mgz0227/legado-Harmony/assets/153937346/1001f49f-d5e0-4a75-8b21-9fb3cf1b27ad)

**Comment by alphires1** [comment]
> 麻烦提供bug截图，经过测试没出现该情况。
![初始化](https://github.com/mgz0227/legado-Harmony/assets/153937346/16c51c30-3e61-4cee-a038-071ffd4f88e1)
![点击漫画标签之后，小说标签的背景](https://github.com/mgz0227/legado-Harmony/assets/153937346/d7fd82eb-51d6-4be8-8735-c91302330329)
![点击有声书标签之后，前两个标签的背景](https://github.com/mgz0227/legado-Harmony/assets/153937346/a2643a1a-edc9-44d7-84ac-46213b8cd80e)

**Comment by mgz0227** [comment]
请拉取最新源码后使用模拟器进行测试
