### ISSUE TITLE
怎么参与到开发中来

### ISSUE THREAD

**Issue by yi-boide** [mgz0227/legado-Harmony#156]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

怎么参与到开发中来，我想参与进来。

### 期望实现方式 / How to implement

怎么参与到开发中来

**Comment by mgz0227** [comment]
有哪些开发经验吗？

**Comment by yi-boide** [comment]
> 有哪些开发经验吗？

前端开发，flutter 开发

**Comment by mgz0227** [comment]
请发邮件至miaogongzi0227@gmail.com 会回复你相关内容
