### ISSUE TITLE
webdav账号填入类型只能填数字，应该换成Normal模式

### ISSUE THREAD

**Issue by Tlntin** [mgz0227/legado-Harmony#266]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新版依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

WebDav云盘登陆界面，账号处只能填数字

### 复现步骤 / How to reproduce

刚刚拉取的最新代码，编译运行，打开阅读app-打开我的-云盘登陆，只能输入数字，没办法输入邮箱信息。
建议修改此处代码：[源码](https://github.com/mgz0227/legado-Harmony/blob/main/entry/src/main/ets/pages/view/myCenter/WebDav.ets#L17)
- 修改前
```js
new Input_items("","账号",InputType.Number),
```
- 修改后
```js
new Input_items("","账号",InputType.Normal),
```

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

V4.1.13

### Harmony OS版本 / Harmony OS version

鸿蒙OS5.0.beta3

### 机型 / Model

Mate 60 Pro

**Comment by mgz0227** [comment]
已修复
