### ISSUE TITLE
task.isDone() 报错

### ISSUE THREAD

**Issue by dingjianjaja** [mgz0227/legado-Harmony#276]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新版依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

![截屏2024-11-01 15 01 11](https://github.com/user-attachments/assets/803bcde7-b846-4007-a471-eeb004418eb2)
在官方类Task中没有搜索到方法，请问是版本不同吗
![WechatIMG109975](https://github.com/user-attachments/assets/c0b185e6-7878-481a-8779-c935e89e48c5)

### 复现步骤 / How to reproduce

打开项目运行报错

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

1.1

### Harmony OS版本 / Harmony OS version

Harmony OS 4

### 机型 / Model

模拟器

**Comment by mgz0227** [comment]
目前运行打包均为正常，请详细检查log
